language: go

go:
  - "1.12.x"

before_install:
  - go get -t github.com/codeclimate/test-reporter
  - go get -u golang.org/x/lint/golint
  - golint ./...
  - go vet ./...
  - go build

before_script:
  - test-reporter before-build

script:
  - go test -timeout 180s -coverprofile c.out ./...

after_script:
  - test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
